In [2]:
import pandas as pd

df = pd.read_csv("emi_cleaned.csv")

df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38.0,Female,Married,Professional,82600.0,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38.0,Female,Married,Graduate,21500.0,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38.0,Male,Married,Professional,86100.0,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58.0,Female,Married,High School,66800.0,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48.0,Female,Married,Professional,57300.0,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

## Total Expenses

In [3]:
df["total_expenses"] = (
    df["monthly_rent"]
    + df["school_fees"]
    + df["college_fees"]
    + df["travel_expenses"]
    + df["groceries_utilities"]
    + df["other_monthly_expenses"]
)

## Debt-to-Income Ratio

In [4]:
df["debt_to_income_ratio"] = (
    df["current_emi_amount"]
    / df["monthly_salary"]
)

## Expense Ratio

In [5]:
df["expense_ratio"] = (
    df["total_expenses"]
    / df["monthly_salary"]
)

## Savings Ratio

In [6]:
df["savings_ratio"] = (
    (df["bank_balance"] + df["emergency_fund"])
    / df["monthly_salary"]
)

## Financial Cushion

In [7]:
df["financial_cushion"] = (
    df["bank_balance"]
    + df["emergency_fund"]
)

## Employment Stability

In [8]:
df["employment_stability"] = (
    df["years_of_employment"]
    * df["credit_score"]
)

## Loan Burden Ratio

In [9]:
df["loan_burden_ratio"] = (
    df["requested_amount"]
    / df["monthly_salary"]
)

## Available Income

In [10]:
df["available_income"] = (
    df["monthly_salary"]
    - df["total_expenses"]
    - df["current_emi_amount"]
)

In [11]:
new_features = [
    "total_expenses",
    "debt_to_income_ratio",
    "expense_ratio",
    "savings_ratio",
    "financial_cushion",
    "employment_stability",
    "loan_burden_ratio",
    "available_income"
]

df[new_features].head()

,total_expenses,debt_to_income_ratio,expense_ratio,savings_ratio,financial_cushion,employment_stability,loan_burden_ratio,available_income
0,59900.0,0.286925,0.725182,4.520581,373400.0,594.0,10.290557,-1000.0
1,15400.0,0.190698,0.716279,5.553488,119400.0,4998.0,5.953488,2000.0
2,35600.0,0.000000,0.413473,11.571429,996300.0,3770.0,3.554007,50500.0
3,37400.0,0.000000,0.559880,9.266467,619000.0,1507.0,4.550898,29400.0
4,58600.0,0.000000,1.022688,2.190227,125500.0,2618.0,4.397906,-1300.0

In [12]:
df.select_dtypes(include=["int64","float64"]).columns

Index(['age', 'monthly_salary', 'years_of_employment', 'monthly_rent',
       'family_size', 'dependents', 'school_fees', 'college_fees',
       'travel_expenses', 'groceries_utilities', 'other_monthly_expenses',
       'current_emi_amount', 'credit_score', 'bank_balance', 'emergency_fund',
       'requested_amount', 'requested_tenure', 'max_monthly_emi',
       'total_expenses', 'debt_to_income_ratio', 'expense_ratio',
       'savings_ratio', 'financial_cushion', 'employment_stability',
       'loan_burden_ratio', 'available_income'],
      dtype='str')

In [13]:
df.to_csv(
    "emi_feature_engineered.csv",
    index=False
)

print("Feature engineered dataset saved")

Feature engineered dataset saved

In [14]:
num_df = df.select_dtypes(include=["int64","float64"])

corr = (
    num_df.corr()["max_monthly_emi"]
    .abs()
    .sort_values(ascending=False)
)

corr.head(20)

max_monthly_emi           1.000000
groceries_utilities       0.484695
bank_balance              0.456028
financial_cushion         0.453486
travel_expenses           0.440948
available_income          0.423534
emergency_fund            0.414036
other_monthly_expenses    0.382055
monthly_salary            0.378284
debt_to_income_ratio      0.288506
expense_ratio             0.266512
college_fees              0.258842
current_emi_amount        0.242434
credit_score              0.228814
school_fees               0.215234
loan_burden_ratio         0.179878
monthly_rent              0.169423
total_expenses            0.106481
savings_ratio             0.063079
family_size               0.062266
Name: max_monthly_emi, dtype: float64